import containerQueries from '@tailwindcss/container-queries';
import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    // Puck Views delegate to these copied production components at render time.
    './enigma-components/**/*.{js,jsx,ts,tsx}',
    './lib/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      // =======================================================================
      // COLOR SYSTEM - Theme-controlled via CSS variables
      // All colors use CSS variables generated by css_theme_agent
      // =======================================================================
      colors: {
        // --- Core Brand Palette ---
        'primary': 'var(--color-primary)',
        'primary-light': 'var(--color-primary-light)',
        'primary-dark': 'var(--color-primary-dark)',
        'primary-50': 'var(--color-primary-50)',
        'primary-100': 'var(--color-primary-100)',
        'primary-200': 'var(--color-primary-200)',
        'primary-300': 'var(--color-primary-300)',
        'primary-400': 'var(--color-primary-400)',
        'primary-500': 'var(--color-primary-500)',
        'primary-600': 'var(--color-primary-600)',
        'primary-700': 'var(--color-primary-700)',
        'primary-800': 'var(--color-primary-800)',
        'primary-900': 'var(--color-primary-900)',

        'secondary': 'var(--color-secondary)',
        'secondary-light': 'var(--color-secondary-light)',
        'secondary-dark': 'var(--color-secondary-dark)',
        'secondary-50': 'var(--color-secondary-50)',
        'secondary-100': 'var(--color-secondary-100)',
        'secondary-200': 'var(--color-secondary-200)',
        'secondary-300': 'var(--color-secondary-300)',
        'secondary-400': 'var(--color-secondary-400)',
        'secondary-500': 'var(--color-secondary-500)',
        'secondary-600': 'var(--color-secondary-600)',
        'secondary-700': 'var(--color-secondary-700)',
        'secondary-800': 'var(--color-secondary-800)',
        'secondary-900': 'var(--color-secondary-900)',

        'accent': 'var(--color-accent)',
        'accent-light': 'var(--color-accent-light)',
        'accent-dark': 'var(--color-accent-dark)',
        'accent-50': 'var(--color-accent-50)',
        'accent-100': 'var(--color-accent-100)',
        'accent-200': 'var(--color-accent-200)',
        'accent-300': 'var(--color-accent-300)',
        'accent-400': 'var(--color-accent-400)',
        'accent-500': 'var(--color-accent-500)',
        'accent-600': 'var(--color-accent-600)',
        'accent-700': 'var(--color-accent-700)',
        'accent-800': 'var(--color-accent-800)',
        'accent-900': 'var(--color-accent-900)',

        // --- Text Colors ---
        'text-base': 'var(--color-text-base)',
        'text-muted': 'var(--color-text-muted)',
        'text-light': 'var(--color-text-light)',
        'text-lighter': 'var(--color-text-lighter)',
        'text-inverse': 'var(--color-text-inverse)',
        'text-disabled': 'var(--color-text-disabled)',
        'on-primary': 'var(--color-on-primary)',
        'on-secondary': 'var(--color-on-secondary)',
        'on-accent': 'var(--color-on-accent)',
        'on-success': 'var(--color-on-success)',
        'on-warning': 'var(--color-on-warning)',
        'on-danger': 'var(--color-on-danger)',
        'on-info': 'var(--color-on-info)',

        // --- Background & Surface Colors ---
        'bg-base': 'var(--color-bg-base)',
        'bg-surface': 'var(--color-bg-surface)',
        'bg-elevated': 'var(--color-bg-elevated)',
        'bg-sunken': 'var(--color-bg-sunken)',
        'bg-overlay': 'var(--color-bg-overlay)',
        'bg-hover': 'var(--color-bg-hover)',
        'bg-active': 'var(--color-bg-active)',
        'bg-selected': 'var(--color-bg-selected)',
        'bg-disabled': 'var(--color-bg-disabled)',
        'bg-skeleton': 'var(--color-bg-skeleton)',

        // --- Border Colors ---
        'border': 'var(--color-border)',
        'border-light': 'var(--color-border-light)',
        'border-dark': 'var(--color-border-dark)',
        'border-focus': 'var(--color-border-focus)',
        'border-error': 'var(--color-border-error)',
        'border-success': 'var(--color-border-success)',
        'border-hover': 'var(--color-border-hover)',
        'divider': 'var(--color-divider)',

        // --- State & Feedback Colors ---
        'success': 'var(--color-success)',
        'success-light': 'var(--color-success-light)',
        'success-dark': 'var(--color-success-dark)',
        'success-subtle': 'var(--color-success-subtle)',

        'warning': 'var(--color-warning)',
        'warning-light': 'var(--color-warning-light)',
        'warning-dark': 'var(--color-warning-dark)',
        'warning-subtle': 'var(--color-warning-subtle)',

        'danger': 'var(--color-danger)',
        'danger-light': 'var(--color-danger-light)',
        'danger-dark': 'var(--color-danger-dark)',
        'danger-subtle': 'var(--color-danger-subtle)',

        'info': 'var(--color-info)',
        'info-light': 'var(--color-info-light)',
        'info-dark': 'var(--color-info-dark)',
        'info-subtle': 'var(--color-info-subtle)',

        // --- Interactive & CTA Colors ---
        'cta-primary': 'var(--color-cta-primary)',
        'cta-primary-hover': 'var(--color-cta-primary-hover)',
        'cta-secondary': 'var(--color-cta-secondary)',
        'cta-secondary-hover': 'var(--color-cta-secondary-hover)',

        'link': 'var(--color-link)',
        'link-hover': 'var(--color-link-hover)',
        'link-visited': 'var(--color-link-visited)',

        // --- eCommerce-Specific Colors ---
        'badge': 'var(--color-badge)',
        'badge-text': 'var(--color-badge-text)',
        'badge-sale': 'var(--color-badge-sale)',
        'badge-sale-text': 'var(--color-badge-sale-text)',
        'badge-new': 'var(--color-badge-new)',
        'badge-new-text': 'var(--color-badge-new-text)',

        'highlight': 'var(--color-highlight)',
        'highlight-subtle': 'var(--color-highlight-subtle)',
        'price': 'var(--color-price)',
        'price-sale': 'var(--color-price-sale)',
        'price-original': 'var(--color-price-original)',
        'rating': 'var(--color-rating)',
        'rating-empty': 'var(--color-rating-empty)',
        'stock-low': 'var(--color-stock-low)',
        'stock-out': 'var(--color-stock-out)',
        'stock-available': 'var(--color-stock-available)',

        // --- Input Colors ---
        'input-bg': 'var(--color-input-bg)',
        'input-border': 'var(--color-input-border)',
        'input-border-focus': 'var(--color-input-border-focus)',
        'input-placeholder': 'var(--color-input-placeholder)',

        // --- Navigation Colors ---
        'nav-bg': 'var(--color-nav-bg)',
        'nav-text': 'var(--color-nav-text)',
        'nav-text-hover': 'var(--color-nav-text-hover)',
        'nav-text-active': 'var(--color-nav-text-active)',

        // --- Footer Colors ---
        'footer-bg': 'var(--color-footer-bg)',
        'footer-text': 'var(--color-footer-text)',
        'footer-link': 'var(--color-footer-link)',
        'footer-link-hover': 'var(--color-footer-link-hover)',
      },

      // =======================================================================
      // BORDER RADIUS - Theme-controlled
      // =======================================================================
      borderRadius: {
        'button': 'var(--radius-button)',
        'button-sm': 'var(--radius-button-sm)',
        'button-lg': 'var(--radius-button-lg)',
        'card': 'var(--radius-card)',
        'card-sm': 'var(--radius-card-sm)',
        'card-lg': 'var(--radius-card-lg)',
        'input': 'var(--radius-input)',
        'badge': 'var(--radius-badge)',
        'tag': 'var(--radius-tag)',
        'modal': 'var(--radius-modal)',
        'dropdown': 'var(--radius-dropdown)',
        'tooltip': 'var(--radius-tooltip)',
        'image': 'var(--radius-image)',
        'avatar': 'var(--radius-avatar)',
      },

      // =======================================================================
      // BOX SHADOW - Theme-controlled
      // =======================================================================
      boxShadow: {
        'card': 'var(--shadow-card)',
        'card-hover': 'var(--shadow-card-hover)',
        'button': 'var(--shadow-button)',
        'button-hover': 'var(--shadow-button-hover)',
        'input': 'var(--shadow-input)',
        'input-focus': 'var(--shadow-input-focus)',
        'focus': 'var(--shadow-focus)',
        'focus-ring': 'var(--shadow-focus-ring)',
        'modal': 'var(--shadow-modal)',
        'dropdown': 'var(--shadow-dropdown)',
        'tooltip': 'var(--shadow-tooltip)',
        'navbar': 'var(--shadow-navbar)',
        'product': 'var(--shadow-product)',
        'product-hover': 'var(--shadow-product-hover)',
        'floating': 'var(--shadow-floating)',
      },

      // =======================================================================
      // FONT FAMILY - Theme-controlled (typeface choice only)
      // Note: Font sizes are component-controlled using Tailwind defaults
      // =======================================================================
      fontFamily: {
        'sans': 'var(--font-sans)',
        'serif': 'var(--font-serif)',
        'mono': 'var(--font-mono)',
        'heading': 'var(--font-heading)',
        'body': 'var(--font-body)',
        'display': 'var(--font-display)',
      },

      // =======================================================================
      // TRANSITIONS - Theme-controlled
      // =======================================================================
      transitionDuration: {
        'fast': 'var(--transition-duration-fast)',
        'normal': 'var(--transition-duration-normal)',
        'slow': 'var(--transition-duration-slow)',
      },

      transitionTimingFunction: {
        'default': 'var(--transition-easing-default)',
        'bounce': 'var(--transition-easing-bounce)',
      },

      // =======================================================================
      // Z-INDEX - Theme-controlled (consistent layering)
      // =======================================================================
      zIndex: {
        'dropdown': 'var(--z-dropdown)',
        'sticky': 'var(--z-sticky)',
        'fixed': 'var(--z-fixed)',
        'drawer': 'var(--z-drawer)',
        'modal-backdrop': 'var(--z-modal-backdrop)',
        'modal': 'var(--z-modal)',
        'popover': 'var(--z-popover)',
        'tooltip': 'var(--z-tooltip)',
        'toast': 'var(--z-toast)',
      },

      // =======================================================================
      // BACKDROP BLUR - Theme-controlled
      // =======================================================================
      backdropBlur: {
        'nav': 'var(--backdrop-blur-nav)',
        'modal': 'var(--backdrop-blur-modal)',
        'overlay': 'var(--backdrop-blur-overlay)',
      },

      // =======================================================================
      // OPACITY - Theme-controlled
      // =======================================================================
      opacity: {
        'overlay': 'var(--opacity-overlay)',
        'overlay-light': 'var(--opacity-overlay-light)',
        'overlay-dark': 'var(--opacity-overlay-dark)',
        'disabled': 'var(--opacity-disabled)',
      },

      // =======================================================================
      // ANIMATIONS - Built-in, no CSS variables needed
      // These animations are useful for all themes
      // =======================================================================
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'fade-out': 'fadeOut 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'spin-slow': 'spin 2s linear infinite',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'skeleton': 'skeleton 1.5s ease-in-out infinite',
      },

      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        skeleton: {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '0.7' },
        },
      },
    },
  },
  plugins: [
    containerQueries,
  ],
};

export default config;
