// AUTO-GENERATED by scripts/generate-puck-config.ts
// Do not edit manually — run "npm run generate:puck-config" to regenerate
// Client config — used by Puck editor (no data fetching)

import React from "react";

import { AccountAddressesStateSectionView, puckFields as AccountAddressesStateSection_fields, puckDefaults as AccountAddressesStateSection_defaults } from "@/components/account/AccountAddressesStateSectionView";
import { AccountDashboardView, puckFields as AccountDashboard_fields, puckDefaults as AccountDashboard_defaults } from "@/components/account/AccountDashboardView";
import { AccountDigitalLibraryStateSectionView, puckFields as AccountDigitalLibraryStateSection_fields, puckDefaults as AccountDigitalLibraryStateSection_defaults } from "@/components/account/AccountDigitalLibraryStateSectionView";
import { AccountLinkGridView, puckFields as AccountLinkGrid_fields, puckDefaults as AccountLinkGrid_defaults } from "@/components/account/AccountLinkGridView";
import { AccountSessionPanelView, puckFields as AccountSessionPanel_fields, puckDefaults as AccountSessionPanel_defaults } from "@/components/account/AccountSessionPanelView";
import { AccountSessionsView, puckFields as AccountSessions_fields, puckDefaults as AccountSessions_defaults } from "@/components/account/AccountSessionsView";
import { AccountSettingsView, puckFields as AccountSettings_fields, puckDefaults as AccountSettings_defaults } from "@/components/account/AccountSettingsView";
import { ActiveFiltersBlockView, puckFields as ActiveFiltersBlock_fields, puckDefaults as ActiveFiltersBlock_defaults } from "@/components/products/ActiveFiltersBlockView";
import { AddressListView, puckFields as AddressList_fields, puckDefaults as AddressList_defaults } from "@/components/account/AddressListView";
import { AdminNotesView, puckFields as AdminNotes_fields, puckDefaults as AdminNotes_defaults } from "@/components/account/AdminNotesView";
import { AuthEntryCardView, puckFields as AuthEntryCard_fields, puckDefaults as AuthEntryCard_defaults } from "@/components/auth/AuthEntryCardView";
import { BillingAddressView, puckFields as BillingAddress_fields, puckDefaults as BillingAddress_defaults } from "@/components/account/BillingAddressView";
import { BreadcrumbsView, puckFields as Breadcrumbs_fields, puckDefaults as Breadcrumbs_defaults } from "@/components/products/BreadcrumbsView";
import { CalloutCardView, puckFields as CalloutCard_fields, puckDefaults as CalloutCard_defaults } from "@/components/layout/CalloutCardView";
import { CardSectionView, puckFields as CardSection_fields, puckDefaults as CardSection_defaults } from "@/components/layout/CardSectionView";
import { CartContinueShoppingView, puckFields as CartContinueShopping_fields, puckDefaults as CartContinueShopping_defaults } from "@/components/cart/CartContinueShoppingView";
import { CartEmptyView, puckFields as CartEmpty_fields, puckDefaults as CartEmpty_defaults } from "@/components/cart/CartEmptyView";
import { CartHeaderView, puckFields as CartHeader_fields, puckDefaults as CartHeader_defaults } from "@/components/cart/CartHeaderView";
import { CartListView, puckFields as CartList_fields, puckDefaults as CartList_defaults } from "@/components/cart/CartListView";
import { CartStateSectionView, puckFields as CartStateSection_fields, puckDefaults as CartStateSection_defaults } from "@/components/cart/CartStateSectionView";
import { CartSummaryView, puckFields as CartSummary_fields, puckDefaults as CartSummary_defaults } from "@/components/cart/CartSummaryView";
import { CatalogActiveFiltersBoundaryView, puckFields as CatalogActiveFiltersBoundary_fields, puckDefaults as CatalogActiveFiltersBoundary_defaults } from "@/components/products/canonical/CatalogActiveFiltersBoundaryView";
import { CatalogBreadcrumbsView, puckFields as CatalogBreadcrumbs_fields, puckDefaults as CatalogBreadcrumbs_defaults } from "@/components/products/canonical/CatalogBreadcrumbsView";
import { CatalogContentLayoutView, puckFields as CatalogContentLayout_fields, puckDefaults as CatalogContentLayout_defaults } from "@/components/products/canonical/CatalogContentLayoutView";
import { CatalogControlsLayoutView, puckFields as CatalogControlsLayout_fields, puckDefaults as CatalogControlsLayout_defaults } from "@/components/products/canonical/CatalogControlsLayoutView";
import { CatalogFilterSidebarView, puckFields as CatalogFilterSidebar_fields, puckDefaults as CatalogFilterSidebar_defaults } from "@/components/products/canonical/CatalogFilterSidebarView";
import { CatalogGridBoundaryView, puckFields as CatalogGridBoundary_fields, puckDefaults as CatalogGridBoundary_defaults } from "@/components/products/canonical/CatalogGridBoundaryView";
import { CatalogHeaderLayoutView, puckFields as CatalogHeaderLayout_fields, puckDefaults as CatalogHeaderLayout_defaults } from "@/components/products/canonical/CatalogHeaderLayoutView";
import { CatalogHeadingView, puckFields as CatalogHeading_fields, puckDefaults as CatalogHeading_defaults } from "@/components/products/CatalogHeadingView";
import { CatalogPaginationBlockView, puckFields as CatalogPaginationBlock_fields, puckDefaults as CatalogPaginationBlock_defaults } from "@/components/products/CatalogPaginationBlockView";
import { CatalogPaginationConditionView, puckFields as CatalogPaginationCondition_fields, puckDefaults as CatalogPaginationCondition_defaults } from "@/components/products/canonical/CatalogPaginationConditionView";
import { CatalogResultsStateView, puckFields as CatalogResultsState_fields, puckDefaults as CatalogResultsState_defaults } from "@/components/products/canonical/CatalogResultsStateView";
import { CatalogTitleSummaryView, puckFields as CatalogTitleSummary_fields, puckDefaults as CatalogTitleSummary_defaults } from "@/components/products/canonical/CatalogTitleSummaryView";
import { CategoriesPageBreadcrumbsView, puckFields as CategoriesPageBreadcrumbs_fields, puckDefaults as CategoriesPageBreadcrumbs_defaults } from "@/components/categories/canonical/CategoriesPageBreadcrumbsView";
import { CategoriesPageIntroView, puckFields as CategoriesPageIntro_fields, puckDefaults as CategoriesPageIntro_defaults } from "@/components/categories/canonical/CategoriesPageIntroView";
import { CategoriesPageLayoutView, puckFields as CategoriesPageLayout_fields, puckDefaults as CategoriesPageLayout_defaults } from "@/components/categories/canonical/CategoriesPageLayoutView";
import { CategoryCatalogBreadcrumbsView, puckFields as CategoryCatalogBreadcrumbs_fields, puckDefaults as CategoryCatalogBreadcrumbs_defaults } from "@/components/categories/canonical/CategoryCatalogBreadcrumbsView";
import { CategoryCatalogFilterSidebarView, puckFields as CategoryCatalogFilterSidebar_fields, puckDefaults as CategoryCatalogFilterSidebar_defaults } from "@/components/categories/canonical/CategoryCatalogFilterSidebarView";
import { CategoryCatalogGridBoundaryView, puckFields as CategoryCatalogGridBoundary_fields, puckDefaults as CategoryCatalogGridBoundary_defaults } from "@/components/categories/canonical/CategoryCatalogGridBoundaryView";
import { CategoryCatalogLayoutView, puckFields as CategoryCatalogLayout_fields, puckDefaults as CategoryCatalogLayout_defaults } from "@/components/categories/canonical/CategoryCatalogLayoutView";
import { CategoryCatalogPaginationBlockView, puckFields as CategoryCatalogPaginationBlock_fields, puckDefaults as CategoryCatalogPaginationBlock_defaults } from "@/components/categories/canonical/CategoryCatalogPaginationBlockView";
import { CategoryCatalogPaginationConditionView, puckFields as CategoryCatalogPaginationCondition_fields, puckDefaults as CategoryCatalogPaginationCondition_defaults } from "@/components/categories/canonical/CategoryCatalogPaginationConditionView";
import { CategoryCatalogResultsHeaderView, puckFields as CategoryCatalogResultsHeader_fields, puckDefaults as CategoryCatalogResultsHeader_defaults } from "@/components/categories/canonical/CategoryCatalogResultsHeaderView";
import { CategoryCatalogResultsStateView, puckFields as CategoryCatalogResultsState_fields, puckDefaults as CategoryCatalogResultsState_defaults } from "@/components/categories/canonical/CategoryCatalogResultsStateView";
import { CategoryCatalogStateSectionView, puckFields as CategoryCatalogStateSection_fields, puckDefaults as CategoryCatalogStateSection_defaults } from "@/components/categories/CategoryCatalogStateSectionView";
import { CategoryGridView, puckFields as CategoryGrid_fields, puckDefaults as CategoryGrid_defaults } from "@/components/categories/CategoryGridView";
import { CategoryHeroView, puckFields as CategoryHero_fields, puckDefaults as CategoryHero_defaults } from "@/components/categories/CategoryHeroView";
import { CategoryHighlightsView, puckFields as CategoryHighlights_fields, puckDefaults as CategoryHighlights_defaults } from "@/components/home/CategoryHighlightsView";
import { CategoryProductFiltersBlockView, puckFields as CategoryProductFiltersBlock_fields, puckDefaults as CategoryProductFiltersBlock_defaults } from "@/components/categories/canonical/CategoryProductFiltersBlockView";
import { CategoryProductGridBlockView, puckFields as CategoryProductGridBlock_fields, puckDefaults as CategoryProductGridBlock_defaults } from "@/components/categories/canonical/CategoryProductGridBlockView";
import { CategorySubcategoryConditionView, puckFields as CategorySubcategoryCondition_fields, puckDefaults as CategorySubcategoryCondition_defaults } from "@/components/categories/canonical/CategorySubcategoryConditionView";
import { CheckoutConfirmationView, puckFields as CheckoutConfirmation_fields, puckDefaults as CheckoutConfirmation_defaults } from "@/components/checkout/CheckoutConfirmationView";
import { CheckoutDigitalAssetsSectionView, puckFields as CheckoutDigitalAssetsSection_fields, puckDefaults as CheckoutDigitalAssetsSection_defaults } from "@/components/checkout/success/CheckoutDigitalAssetsSectionView";
import { CheckoutOrderReviewView, puckFields as CheckoutOrderReview_fields, puckDefaults as CheckoutOrderReview_defaults } from "@/components/checkout/CheckoutOrderReviewView";
import { CheckoutOrderSummaryView, puckFields as CheckoutOrderSummary_fields, puckDefaults as CheckoutOrderSummary_defaults } from "@/components/checkout/CheckoutOrderSummaryView";
import { CheckoutPaymentMethodView, puckFields as CheckoutPaymentMethod_fields, puckDefaults as CheckoutPaymentMethod_defaults } from "@/components/checkout/CheckoutPaymentMethodView";
import { CheckoutPlaceOrderButtonView, puckFields as CheckoutPlaceOrderButton_fields, puckDefaults as CheckoutPlaceOrderButton_defaults } from "@/components/checkout/CheckoutPlaceOrderButtonView";
import { CheckoutSecureBadgesView, puckFields as CheckoutSecureBadges_fields, puckDefaults as CheckoutSecureBadges_defaults } from "@/components/checkout/CheckoutSecureBadgesView";
import { CheckoutShippingFormView, puckFields as CheckoutShippingForm_fields, puckDefaults as CheckoutShippingForm_defaults } from "@/components/checkout/CheckoutShippingFormView";
import { CheckoutShippingMethodView, puckFields as CheckoutShippingMethod_fields, puckDefaults as CheckoutShippingMethod_defaults } from "@/components/checkout/CheckoutShippingMethodView";
import { CheckoutStateSectionView, puckFields as CheckoutStateSection_fields, puckDefaults as CheckoutStateSection_defaults } from "@/components/checkout/CheckoutStateSectionView";
import { CheckoutStepsView, puckFields as CheckoutSteps_fields, puckDefaults as CheckoutSteps_defaults } from "@/components/checkout/CheckoutStepsView";
import { CheckoutSubscriptionStateSectionView, puckFields as CheckoutSubscriptionStateSection_fields, puckDefaults as CheckoutSubscriptionStateSection_defaults } from "@/components/checkout/CheckoutSubscriptionStateSectionView";
import { CollectionDetailStateSectionView, puckFields as CollectionDetailStateSection_fields, puckDefaults as CollectionDetailStateSection_defaults } from "@/components/collections/CollectionDetailStateSectionView";
import { CollectionGridView, puckFields as CollectionGrid_fields, puckDefaults as CollectionGrid_defaults } from "@/components/collections/CollectionGridView";
import { CollectionHeroView, puckFields as CollectionHero_fields, puckDefaults as CollectionHero_defaults } from "@/components/collections/CollectionHeroView";
import { CollectionStateSectionView, puckFields as CollectionStateSection_fields, puckDefaults as CollectionStateSection_defaults } from "@/components/collections/CollectionStateSectionView";
import { ConditionalSectionView, puckFields as ConditionalSection_fields, puckDefaults as ConditionalSection_defaults } from "@/components/layout/ConditionalSectionView";
import { OrderSummaryView, puckFields as ConfirmationOrderSummary_fields, puckDefaults as ConfirmationOrderSummary_defaults } from "@/components/checkout/success/OrderSummaryView";
import { ContinueShoppingButtonView, puckFields as ContinueShoppingButton_fields, puckDefaults as ContinueShoppingButton_defaults } from "@/components/checkout/success/ContinueShoppingButtonView";
import { CuratedCollectionSectionView, puckFields as CuratedCollectionSection_fields, puckDefaults as CuratedCollectionSection_defaults } from "@/components/home/CuratedCollectionSectionView";
import { CuratedProductDisplayView, puckFields as CuratedProductDisplay_fields, puckDefaults as CuratedProductDisplay_defaults } from "@/components/collections/CuratedProductDisplayView";
import { DepartmentCategoriesSectionView, puckFields as DepartmentCategoriesSection_fields, puckDefaults as DepartmentCategoriesSection_defaults } from "@/components/categories/canonical/DepartmentCategoriesSectionView";
import { DigitalDownloadsView, puckFields as DigitalDownloads_fields, puckDefaults as DigitalDownloads_defaults } from "@/components/checkout/success/DigitalDownloadsView";
import { DownloadLicenseStateSectionView, puckFields as DownloadLicenseStateSection_fields, puckDefaults as DownloadLicenseStateSection_defaults } from "@/components/downloads/DownloadLicenseStateSectionView";
import { DownloadsEmptyView, puckFields as DownloadsEmpty_fields, puckDefaults as DownloadsEmpty_defaults } from "@/components/account/DownloadsEmptyView";
import { EmptyCategoryView, puckFields as EmptyCategory_fields, puckDefaults as EmptyCategory_defaults } from "@/components/categories/EmptyCategoryView";
import { EmptyCollectionsView, puckFields as EmptyCollections_fields, puckDefaults as EmptyCollections_defaults } from "@/components/collections/EmptyCollectionsView";
import { EmptyPaymentMethodsView, puckFields as EmptyPaymentMethods_fields, puckDefaults as EmptyPaymentMethods_defaults } from "@/components/account/EmptyPaymentMethodsView";
import { EmptyStateView, puckFields as EmptyState_fields, puckDefaults as EmptyState_defaults } from "@/components/products/EmptyStateView";
import { ErrorStateView, puckFields as ErrorState_fields, puckDefaults as ErrorState_defaults } from "@/components/layout/ErrorStateView";
import { FeaturedProductsGridView, puckFields as FeaturedProductsGrid_fields, puckDefaults as FeaturedProductsGrid_defaults } from "@/components/home/FeaturedProductsGridView";
import { FeatureIconListView, puckFields as FeatureIconList_fields, puckDefaults as FeatureIconList_defaults } from "@/components/layout/FeatureIconListView";
import { FreeShippingProgressView, puckFields as FreeShippingProgress_fields, puckDefaults as FreeShippingProgress_defaults } from "@/components/cart/FreeShippingProgressView";
import { HeroSectionView, puckFields as HeroSection_fields, puckDefaults as HeroSection_defaults } from "@/components/home/HeroSectionView";
import { InspirationGalleryView, puckFields as InspirationGallery_fields, puckDefaults as InspirationGallery_defaults } from "@/components/collections/InspirationGalleryView";
import { InspirationSectionView, puckFields as InspirationSection_fields, puckDefaults as InspirationSection_defaults } from "@/components/home/InspirationSectionView";
import { LicenseKeyDisplayView, puckFields as LicenseKeyDisplay_fields, puckDefaults as LicenseKeyDisplay_defaults } from "@/components/checkout/success/LicenseKeyDisplayView";
import { MobileFilterDrawerBlockView, puckFields as MobileFilterDrawerBlock_fields, puckDefaults as MobileFilterDrawerBlock_defaults } from "@/components/products/MobileFilterDrawerBlockView";
import { NewsletterSignupView, puckFields as NewsletterSignup_fields, puckDefaults as NewsletterSignup_defaults } from "@/components/home/NewsletterSignupView";
import { NextStepsCardView, puckFields as NextStepsCard_fields, puckDefaults as NextStepsCard_defaults } from "@/components/checkout/success/NextStepsCardView";
import { NoResultsView, puckFields as NoResults_fields, puckDefaults as NoResults_defaults } from "@/components/search/NoResultsView";
import { NotEligibleMessageView, puckFields as NotEligibleMessage_fields, puckDefaults as NotEligibleMessage_defaults } from "@/components/account/NotEligibleMessageView";
import { NotFoundStateView, puckFields as NotFoundState_fields, puckDefaults as NotFoundState_defaults } from "@/components/layout/NotFoundStateView";
import { OrderDetailsView, puckFields as OrderDetails_fields, puckDefaults as OrderDetails_defaults } from "@/components/account/OrderDetailsView";
import { OrderEmptyView, puckFields as OrderEmpty_fields, puckDefaults as OrderEmpty_defaults } from "@/components/account/OrderEmptyView";
import { OrderItemListView, puckFields as OrderItemList_fields, puckDefaults as OrderItemList_defaults } from "@/components/checkout/success/OrderItemListView";
import { OrderNumberView, puckFields as OrderNumber_fields, puckDefaults as OrderNumber_defaults } from "@/components/checkout/success/OrderNumberView";
import { OrderStatusBadgeView, puckFields as OrderStatusBadge_fields, puckDefaults as OrderStatusBadge_defaults } from "@/components/account/OrderStatusBadgeView";
import { PageHeaderView, puckFields as PageHeader_fields, puckDefaults as PageHeader_defaults } from "@/components/layout/PageHeaderView";
import { PageWrapperView, puckFields as PageWrapper_fields, puckDefaults as PageWrapper_defaults } from "@/components/layout/PageWrapperView";
import { PaymentInfoView, puckFields as PaymentInfo_fields, puckDefaults as PaymentInfo_defaults } from "@/components/account/PaymentInfoView";
import { PriceDisplayView, puckFields as PriceDisplay_fields, puckDefaults as PriceDisplay_defaults } from "@/components/products/PriceDisplayView";
import { ProductDetailMediaColumnView, puckFields as ProductDetailMediaColumn_fields, puckDefaults as ProductDetailMediaColumn_defaults } from "@/components/products/canonical/ProductDetailMediaColumnView";
import { ProductDetailMobileTabsView, puckFields as ProductDetailMobileTabs_fields, puckDefaults as ProductDetailMobileTabs_defaults } from "@/components/products/canonical/ProductDetailMobileTabsView";
import { ProductDetailPageLayoutView, puckFields as ProductDetailPageLayout_fields, puckDefaults as ProductDetailPageLayout_defaults } from "@/components/products/canonical/ProductDetailPageLayoutView";
import { ProductDetailPurchaseColumnView, puckFields as ProductDetailPurchaseColumn_fields, puckDefaults as ProductDetailPurchaseColumn_defaults } from "@/components/products/canonical/ProductDetailPurchaseColumnView";
import { ProductDetailPurchaseSectionView, puckFields as ProductDetailPurchaseSection_fields, puckDefaults as ProductDetailPurchaseSection_defaults } from "@/components/products/ProductDetailPurchaseSectionView";
import { ProductDetailRelatedProductsSectionView, puckFields as ProductDetailRelatedProductsSection_fields, puckDefaults as ProductDetailRelatedProductsSection_defaults } from "@/components/products/canonical/ProductDetailRelatedProductsSectionView";
import { ProductDetailsClientView, puckFields as ProductDetailsClient_fields, puckDefaults as ProductDetailsClient_defaults } from "@/components/templates/products/ProductDetailsClientView";
import { ProductDetailSectionView, puckFields as ProductDetailSection_fields, puckDefaults as ProductDetailSection_defaults } from "@/components/products/canonical/ProductDetailSectionView";
import { ProductDetailTrustBadgesView, puckFields as ProductDetailTrustBadges_fields, puckDefaults as ProductDetailTrustBadges_defaults } from "@/components/products/canonical/ProductDetailTrustBadgesView";
import { ProductFiltersBlockView, puckFields as ProductFiltersBlock_fields, puckDefaults as ProductFiltersBlock_defaults } from "@/components/products/ProductFiltersBlockView";
import { ProductGalleryView, puckFields as ProductGallery_fields, puckDefaults as ProductGallery_defaults } from "@/components/products/ProductGalleryView";
import { ProductGridView, puckFields as ProductGrid_fields, puckDefaults as ProductGrid_defaults } from "@/components/products/ProductGridView";
import { ProductRatingSummaryView, puckFields as ProductRatingSummary_fields, puckDefaults as ProductRatingSummary_defaults } from "@/components/templates/products/ProductRatingSummaryView";
import { ProductRelatedProductsSectionView, puckFields as ProductRelatedProductsSection_fields, puckDefaults as ProductRelatedProductsSection_defaults } from "@/components/products/ProductRelatedProductsSectionView";
import { ProductsCatalogLayoutView, puckFields as ProductsCatalogLayout_fields, puckDefaults as ProductsCatalogLayout_defaults } from "@/components/products/canonical/ProductsCatalogLayoutView";
import { ProductsCatalogStateSectionView, puckFields as ProductsCatalogStateSection_fields, puckDefaults as ProductsCatalogStateSection_defaults } from "@/components/products/ProductsCatalogStateSectionView";
import { ProductTabsView, puckFields as ProductTabs_fields, puckDefaults as ProductTabs_defaults } from "@/components/products/ProductTabsView";
import { PromotionBannerView, puckFields as PromotionBanner_fields, puckDefaults as PromotionBanner_defaults } from "@/components/home/PromotionBannerView";
import { PurchaseTrackerView, puckFields as PurchaseTracker_fields, puckDefaults as PurchaseTracker_defaults } from "@/components/checkout/success/PurchaseTrackerView";
import { RefundSummaryView, puckFields as RefundSummary_fields, puckDefaults as RefundSummary_defaults } from "@/components/account/RefundSummaryView";
import { RelatedProductsView, puckFields as RelatedProducts_fields, puckDefaults as RelatedProducts_defaults } from "@/components/products/RelatedProductsView";
import { ReturnPolicyReminderView, puckFields as ReturnPolicyReminder_fields, puckDefaults as ReturnPolicyReminder_defaults } from "@/components/account/ReturnPolicyReminderView";
import { ReturnReasonView, puckFields as ReturnReason_fields, puckDefaults as ReturnReason_defaults } from "@/components/account/ReturnReasonView";
import { ReturnsEmptyView, puckFields as ReturnsEmpty_fields, puckDefaults as ReturnsEmpty_defaults } from "@/components/account/ReturnsEmptyView";
import { ReturnStatusBadgeView, puckFields as ReturnStatusBadge_fields, puckDefaults as ReturnStatusBadge_defaults } from "@/components/account/ReturnStatusBadgeView";
import { ReturnWindowExpiredView, puckFields as ReturnWindowExpired_fields, puckDefaults as ReturnWindowExpired_defaults } from "@/components/account/ReturnWindowExpiredView";
import { ReviewsSectionView, puckFields as ReviewsSection_fields, puckDefaults as ReviewsSection_defaults } from "@/components/products/ReviewsSectionView";
import { SearchHeaderView, puckFields as SearchHeader_fields, puckDefaults as SearchHeader_defaults } from "@/components/search/SearchHeaderView";
import { SearchStateSectionView, puckFields as SearchStateSection_fields, puckDefaults as SearchStateSection_defaults } from "@/components/search/SearchStateSectionView";
import { SectionHeaderWithDividerView, puckFields as SectionHeaderWithDivider_fields, puckDefaults as SectionHeaderWithDivider_defaults } from "@/components/layout/SectionHeaderWithDividerView";
import { SectionHeadingView, puckFields as SectionHeading_fields, puckDefaults as SectionHeading_defaults } from "@/components/layout/SectionHeadingView";
import { SharedWishlistView, puckFields as SharedWishlist_fields, puckDefaults as SharedWishlist_defaults } from "@/components/account/SharedWishlistView";
import { SharedWishlistStateSectionView, puckFields as SharedWishlistStateSection_fields, puckDefaults as SharedWishlistStateSection_defaults } from "@/components/wishlist/SharedWishlistStateSectionView";
import { ShippingAddressView, puckFields as ShippingAddress_fields, puckDefaults as ShippingAddress_defaults } from "@/components/account/ShippingAddressView";
import { ShippingInfoView, puckFields as ShippingInfo_fields, puckDefaults as ShippingInfo_defaults } from "@/components/checkout/success/ShippingInfoView";
import { SortDropdownBlockView, puckFields as SortDropdownBlock_fields, puckDefaults as SortDropdownBlock_defaults } from "@/components/products/SortDropdownBlockView";
import { StockIndicatorView, puckFields as StockIndicator_fields, puckDefaults as StockIndicator_defaults } from "@/components/products/StockIndicatorView";
import { SubcategoryNavView, puckFields as SubcategoryNav_fields, puckDefaults as SubcategoryNav_defaults } from "@/components/categories/SubcategoryNavView";
import { SubscriptionDetailsHeaderView, puckFields as SubscriptionDetailsHeader_fields, puckDefaults as SubscriptionDetailsHeader_defaults } from "@/components/account/SubscriptionDetailsHeaderView";
import { SubscriptionDetailStateSectionView, puckFields as SubscriptionDetailStateSection_fields, puckDefaults as SubscriptionDetailStateSection_defaults } from "@/components/account/SubscriptionDetailStateSectionView";
import { SubscriptionsEmptyView, puckFields as SubscriptionsEmpty_fields, puckDefaults as SubscriptionsEmpty_defaults } from "@/components/account/SubscriptionsEmptyView";
import { SubscriptionStatusBadgeView, puckFields as SubscriptionStatusBadge_fields, puckDefaults as SubscriptionStatusBadge_defaults } from "@/components/account/SubscriptionStatusBadgeView";
import { SuccessHeaderView, puckFields as SuccessHeader_fields, puckDefaults as SuccessHeader_defaults } from "@/components/checkout/success/SuccessHeaderView";
import { TestimonialsSectionView, puckFields as TestimonialsSection_fields, puckDefaults as TestimonialsSection_defaults } from "@/components/testimonials/TestimonialsSectionView";
import { TrendingCategoriesSectionView, puckFields as TrendingCategoriesSection_fields, puckDefaults as TrendingCategoriesSection_defaults } from "@/components/categories/canonical/TrendingCategoriesSectionView";
import { TrendingCategoryCardView, puckFields as TrendingCategoryCard_fields, puckDefaults as TrendingCategoryCard_defaults } from "@/components/categories/TrendingCategoryCardView";
import { TrustBadges, puckFields as TrustBadges_fields, puckDefaults as TrustBadges_defaults } from "@/components/home/TrustBadges";
import { TwoColumnDetailView, puckFields as TwoColumnDetail_fields, puckDefaults as TwoColumnDetail_defaults } from "@/components/layout/TwoColumnDetailView";
import { ViewOrderButtonView, puckFields as ViewOrderButton_fields, puckDefaults as ViewOrderButton_defaults } from "@/components/checkout/success/ViewOrderButtonView";
import { ViewToggleBlockView, puckFields as ViewToggleBlock_fields, puckDefaults as ViewToggleBlock_defaults } from "@/components/products/ViewToggleBlockView";
import { WishlistEmptyView, puckFields as WishlistEmpty_fields, puckDefaults as WishlistEmpty_defaults } from "@/components/account/WishlistEmptyView";
import { WishlistSavingsCardView, puckFields as WishlistSavingsCard_fields, puckDefaults as WishlistSavingsCard_defaults } from "@/components/account/WishlistSavingsCardView";

const config = {
  categories: {
    "Home": {
      title: "Home",
      defaultExpanded: true,
      components: ["CategoryHighlights", "CuratedCollectionSection", "FeaturedProductsGrid", "HeroSection", "InspirationSection", "NewsletterSignup", "TrustBadges"],
    },
    "Products": {
      title: "Products",
      defaultExpanded: true,
      components: ["ActiveFiltersBlock", "Breadcrumbs", "CatalogActiveFiltersBoundary", "CatalogBreadcrumbs", "CatalogContentLayout", "CatalogControlsLayout", "CatalogFilterSidebar", "CatalogGridBoundary", "CatalogHeaderLayout", "CatalogHeading", "CatalogPaginationBlock", "CatalogPaginationCondition", "CatalogResultsState", "CatalogTitleSummary", "EmptyState", "MobileFilterDrawerBlock", "PriceDisplay", "ProductDetailMediaColumn", "ProductDetailMobileTabs", "ProductDetailPageLayout", "ProductDetailPurchaseColumn", "ProductDetailPurchaseSection", "ProductDetailRelatedProductsSection", "ProductDetailsClient", "ProductDetailSection", "ProductDetailTrustBadges", "ProductFiltersBlock", "ProductGallery", "ProductGrid", "ProductRatingSummary", "ProductRelatedProductsSection", "ProductsCatalogLayout", "ProductsCatalogStateSection", "ProductTabs", "RelatedProducts", "ReviewsSection", "SortDropdownBlock", "StockIndicator", "ViewToggleBlock"],
    },
    "Categories": {
      title: "Categories",
      defaultExpanded: true,
      components: ["CategoriesPageBreadcrumbs", "CategoriesPageIntro", "CategoriesPageLayout", "CategoryCatalogBreadcrumbs", "CategoryCatalogFilterSidebar", "CategoryCatalogGridBoundary", "CategoryCatalogLayout", "CategoryCatalogPaginationBlock", "CategoryCatalogPaginationCondition", "CategoryCatalogResultsHeader", "CategoryCatalogResultsState", "CategoryCatalogStateSection", "CategoryGrid", "CategoryHero", "CategoryProductFiltersBlock", "CategoryProductGridBlock", "CategorySubcategoryCondition", "DepartmentCategoriesSection", "EmptyCategory", "SubcategoryNav", "TrendingCategoriesSection", "TrendingCategoryCard"],
    },
    "Collections": {
      title: "Collections",
      defaultExpanded: false,
      components: ["CollectionDetailStateSection", "CollectionGrid", "CollectionHero", "CollectionStateSection", "CuratedProductDisplay", "EmptyCollections", "InspirationGallery"],
    },
    "Search": {
      title: "Search",
      defaultExpanded: false,
      components: ["NoResults", "SearchHeader", "SearchStateSection"],
    },
    "Cart": {
      title: "Cart",
      defaultExpanded: false,
      components: ["CartContinueShopping", "CartEmpty", "CartHeader", "CartList", "CartStateSection", "CartSummary", "FreeShippingProgress"],
    },
    "Checkout": {
      title: "Checkout",
      defaultExpanded: false,
      components: ["CheckoutConfirmation", "CheckoutDigitalAssetsSection", "CheckoutOrderReview", "CheckoutOrderSummary", "CheckoutPaymentMethod", "CheckoutPlaceOrderButton", "CheckoutSecureBadges", "CheckoutShippingForm", "CheckoutShippingMethod", "CheckoutStateSection", "CheckoutSteps", "CheckoutSubscriptionStateSection", "ConfirmationOrderSummary", "ContinueShoppingButton", "DigitalDownloads", "LicenseKeyDisplay", "NextStepsCard", "OrderItemList", "OrderNumber", "PurchaseTracker", "ShippingInfo", "SuccessHeader", "ViewOrderButton"],
    },
    "Account": {
      title: "Account",
      defaultExpanded: false,
      components: ["AccountAddressesStateSection", "AccountDashboard", "AccountDigitalLibraryStateSection", "AccountLinkGrid", "AccountSessionPanel", "AccountSessions", "AccountSettings", "AddressList", "AdminNotes", "BillingAddress", "DownloadsEmpty", "EmptyPaymentMethods", "NotEligibleMessage", "OrderDetails", "OrderEmpty", "OrderStatusBadge", "PaymentInfo", "RefundSummary", "ReturnPolicyReminder", "ReturnReason", "ReturnsEmpty", "ReturnStatusBadge", "ReturnWindowExpired", "SharedWishlist", "ShippingAddress", "SubscriptionDetailsHeader", "SubscriptionDetailStateSection", "SubscriptionsEmpty", "SubscriptionStatusBadge", "WishlistEmpty", "WishlistSavingsCard"],
    },
    "Social Proof": {
      title: "Social Proof",
      defaultExpanded: false,
      components: ["TestimonialsSection"],
    },
    "Auth": {
      title: "Auth",
      defaultExpanded: false,
      components: ["AuthEntryCard"],
    },
    "Downloads": {
      title: "Downloads",
      defaultExpanded: false,
      components: ["DownloadLicenseStateSection"],
    },
    "Feedback": {
      title: "Feedback",
      defaultExpanded: false,
      components: ["ErrorState", "NotFoundState"],
    },
    "Layout": {
      title: "Layout",
      defaultExpanded: false,
      components: ["CalloutCard", "CardSection", "ConditionalSection", "FeatureIconList", "PageHeader", "PageWrapper", "SectionHeaderWithDivider", "SectionHeading", "TwoColumnDetail"],
    },
    "Marketing": {
      title: "Marketing",
      defaultExpanded: false,
      components: ["PromotionBanner"],
    },
    "Wishlist": {
      title: "Wishlist",
      defaultExpanded: false,
      components: ["SharedWishlistStateSection"],
    },
  },
  components: {
    AccountAddressesStateSection: {
      category: "Account",
      label: "Account Addresses State Section",
      fields: AccountAddressesStateSection_fields,
      defaultProps: AccountAddressesStateSection_defaults,
      render: (props) => <AccountAddressesStateSectionView {...props} />,
    },
    AccountDashboard: {
      category: "Account",
      label: "Account Dashboard",
      fields: AccountDashboard_fields,
      defaultProps: AccountDashboard_defaults,
      render: (props) => <AccountDashboardView {...props} />,
    },
    AccountDigitalLibraryStateSection: {
      category: "Account",
      label: "Account Digital Library State Section",
      fields: AccountDigitalLibraryStateSection_fields,
      defaultProps: AccountDigitalLibraryStateSection_defaults,
      render: (props) => <AccountDigitalLibraryStateSectionView {...props} />,
    },
    AccountLinkGrid: {
      category: "Account",
      label: "Account Link Grid",
      fields: AccountLinkGrid_fields,
      defaultProps: AccountLinkGrid_defaults,
      render: (props) => <AccountLinkGridView {...props} />,
    },
    AccountSessionPanel: {
      category: "Account",
      label: "Account Session Panel",
      fields: AccountSessionPanel_fields,
      defaultProps: AccountSessionPanel_defaults,
      render: (props) => <AccountSessionPanelView {...props} />,
    },
    AccountSessions: {
      category: "Account",
      label: "Account Sessions",
      fields: AccountSessions_fields,
      defaultProps: AccountSessions_defaults,
      render: (props) => <AccountSessionsView {...props} />,
    },
    AccountSettings: {
      category: "Account",
      label: "Account Settings",
      fields: AccountSettings_fields,
      defaultProps: AccountSettings_defaults,
      render: (props) => <AccountSettingsView {...props} />,
    },
    ActiveFiltersBlock: {
      category: "Products",
      label: "Active Product Filters",
      fields: ActiveFiltersBlock_fields,
      defaultProps: ActiveFiltersBlock_defaults,
      render: (props) => <ActiveFiltersBlockView {...props} />,
    },
    AddressList: {
      category: "Account",
      label: "Address List",
      fields: AddressList_fields,
      defaultProps: AddressList_defaults,
      render: (props) => <AddressListView {...props} />,
    },
    AdminNotes: {
      category: "Account",
      label: "Admin Notes",
      fields: AdminNotes_fields,
      defaultProps: AdminNotes_defaults,
      render: (props) => <AdminNotesView {...props} />,
    },
    AuthEntryCard: {
      category: "Auth",
      label: "Auth Entry Card",
      fields: AuthEntryCard_fields,
      defaultProps: AuthEntryCard_defaults,
      render: (props) => <AuthEntryCardView {...props} />,
    },
    BillingAddress: {
      category: "Account",
      label: "Billing Address",
      fields: BillingAddress_fields,
      defaultProps: BillingAddress_defaults,
      render: (props) => <BillingAddressView {...props} />,
    },
    Breadcrumbs: {
      category: "Products",
      label: "Breadcrumbs",
      fields: Breadcrumbs_fields,
      defaultProps: Breadcrumbs_defaults,
      render: (props) => <BreadcrumbsView {...props} />,
    },
    CalloutCard: {
      category: "Layout",
      label: "Callout Card",
      fields: CalloutCard_fields,
      defaultProps: CalloutCard_defaults,
      render: (props) => <CalloutCardView {...props} />,
    },
    CardSection: {
      category: "Layout",
      label: "Card Section",
      fields: CardSection_fields,
      defaultProps: CardSection_defaults,
      render: (props) => <CardSectionView {...props} />,
    },
    CartContinueShopping: {
      category: "Cart",
      label: "Continue Shopping Button",
      fields: CartContinueShopping_fields,
      defaultProps: CartContinueShopping_defaults,
      render: (props) => <CartContinueShoppingView {...props} />,
    },
    CartEmpty: {
      category: "Cart",
      label: "Cart Empty State",
      fields: CartEmpty_fields,
      defaultProps: CartEmpty_defaults,
      render: (props) => <CartEmptyView {...props} />,
    },
    CartHeader: {
      category: "Cart",
      label: "Cart Header",
      fields: CartHeader_fields,
      defaultProps: CartHeader_defaults,
      render: (props) => <CartHeaderView {...props} />,
    },
    CartList: {
      category: "Cart",
      label: "Cart Item List",
      fields: CartList_fields,
      defaultProps: CartList_defaults,
      render: (props) => <CartListView {...props} />,
    },
    CartStateSection: {
      category: "Cart",
      label: "Cart State Section",
      fields: CartStateSection_fields,
      defaultProps: CartStateSection_defaults,
      render: (props) => <CartStateSectionView {...props} />,
    },
    CartSummary: {
      category: "Cart",
      label: "Cart Summary",
      fields: CartSummary_fields,
      defaultProps: CartSummary_defaults,
      render: (props) => <CartSummaryView {...props} />,
    },
    CatalogActiveFiltersBoundary: {
      category: "Products",
      label: "Catalog Active Filters Boundary",
      fields: CatalogActiveFiltersBoundary_fields,
      defaultProps: CatalogActiveFiltersBoundary_defaults,
      render: (props) => <CatalogActiveFiltersBoundaryView {...props} />,
    },
    CatalogBreadcrumbs: {
      category: "Products",
      label: "Catalog Breadcrumbs",
      fields: CatalogBreadcrumbs_fields,
      defaultProps: CatalogBreadcrumbs_defaults,
      render: (props) => <CatalogBreadcrumbsView {...props} />,
    },
    CatalogContentLayout: {
      category: "Products",
      label: "Catalog Content Layout",
      fields: CatalogContentLayout_fields,
      defaultProps: CatalogContentLayout_defaults,
      render: (props) => <CatalogContentLayoutView {...props} />,
    },
    CatalogControlsLayout: {
      category: "Products",
      label: "Catalog Controls Layout",
      fields: CatalogControlsLayout_fields,
      defaultProps: CatalogControlsLayout_defaults,
      render: (props) => <CatalogControlsLayoutView {...props} />,
    },
    CatalogFilterSidebar: {
      category: "Products",
      label: "Catalog Filter Sidebar",
      fields: CatalogFilterSidebar_fields,
      defaultProps: CatalogFilterSidebar_defaults,
      render: (props) => <CatalogFilterSidebarView {...props} />,
    },
    CatalogGridBoundary: {
      category: "Products",
      label: "Catalog Grid Loading Boundary",
      fields: CatalogGridBoundary_fields,
      defaultProps: CatalogGridBoundary_defaults,
      render: (props) => <CatalogGridBoundaryView {...props} />,
    },
    CatalogHeaderLayout: {
      category: "Products",
      label: "Catalog Header Layout",
      fields: CatalogHeaderLayout_fields,
      defaultProps: CatalogHeaderLayout_defaults,
      render: (props) => <CatalogHeaderLayoutView {...props} />,
    },
    CatalogHeading: {
      category: "Products",
      label: "Catalog Heading",
      fields: CatalogHeading_fields,
      defaultProps: CatalogHeading_defaults,
      render: (props) => <CatalogHeadingView {...props} />,
    },
    CatalogPaginationBlock: {
      category: "Products",
      label: "Catalog Pagination",
      fields: CatalogPaginationBlock_fields,
      defaultProps: CatalogPaginationBlock_defaults,
      render: (props) => <CatalogPaginationBlockView {...props} />,
    },
    CatalogPaginationCondition: {
      category: "Products",
      label: "Catalog Pagination Condition",
      fields: CatalogPaginationCondition_fields,
      defaultProps: CatalogPaginationCondition_defaults,
      render: (props) => <CatalogPaginationConditionView {...props} />,
    },
    CatalogResultsState: {
      category: "Products",
      label: "Catalog Results State",
      fields: CatalogResultsState_fields,
      defaultProps: CatalogResultsState_defaults,
      render: (props) => <CatalogResultsStateView {...props} />,
    },
    CatalogTitleSummary: {
      category: "Products",
      label: "Catalog Title and Count",
      fields: CatalogTitleSummary_fields,
      defaultProps: CatalogTitleSummary_defaults,
      render: (props) => <CatalogTitleSummaryView {...props} />,
    },
    CategoriesPageBreadcrumbs: {
      category: "Categories",
      label: "Categories Breadcrumbs",
      fields: CategoriesPageBreadcrumbs_fields,
      defaultProps: CategoriesPageBreadcrumbs_defaults,
      render: (props) => <CategoriesPageBreadcrumbsView {...props} />,
    },
    CategoriesPageIntro: {
      category: "Categories",
      label: "Categories Page Introduction",
      fields: CategoriesPageIntro_fields,
      defaultProps: CategoriesPageIntro_defaults,
      render: (props) => <CategoriesPageIntroView {...props} />,
    },
    CategoriesPageLayout: {
      category: "Categories",
      label: "Categories Page Layout",
      fields: CategoriesPageLayout_fields,
      defaultProps: CategoriesPageLayout_defaults,
      render: (props) => <CategoriesPageLayoutView {...props} />,
    },
    CategoryCatalogBreadcrumbs: {
      category: "Categories",
      label: "Category Breadcrumbs",
      fields: CategoryCatalogBreadcrumbs_fields,
      defaultProps: CategoryCatalogBreadcrumbs_defaults,
      render: (props) => <CategoryCatalogBreadcrumbsView {...props} />,
    },
    CategoryCatalogFilterSidebar: {
      category: "Categories",
      label: "Category Filter Sidebar",
      fields: CategoryCatalogFilterSidebar_fields,
      defaultProps: CategoryCatalogFilterSidebar_defaults,
      render: (props) => <CategoryCatalogFilterSidebarView {...props} />,
    },
    CategoryCatalogGridBoundary: {
      category: "Categories",
      label: "Category Grid Loading Boundary",
      fields: CategoryCatalogGridBoundary_fields,
      defaultProps: CategoryCatalogGridBoundary_defaults,
      render: (props) => <CategoryCatalogGridBoundaryView {...props} />,
    },
    CategoryCatalogLayout: {
      category: "Categories",
      label: "Category Catalog Layout",
      fields: CategoryCatalogLayout_fields,
      defaultProps: CategoryCatalogLayout_defaults,
      render: (props) => <CategoryCatalogLayoutView {...props} />,
    },
    CategoryCatalogPaginationBlock: {
      category: "Categories",
      label: "Category Pagination",
      fields: CategoryCatalogPaginationBlock_fields,
      defaultProps: CategoryCatalogPaginationBlock_defaults,
      render: (props) => <CategoryCatalogPaginationBlockView {...props} />,
    },
    CategoryCatalogPaginationCondition: {
      category: "Categories",
      label: "Category Pagination Condition",
      fields: CategoryCatalogPaginationCondition_fields,
      defaultProps: CategoryCatalogPaginationCondition_defaults,
      render: (props) => <CategoryCatalogPaginationConditionView {...props} />,
    },
    CategoryCatalogResultsHeader: {
      category: "Categories",
      label: "Category Results Controls",
      fields: CategoryCatalogResultsHeader_fields,
      defaultProps: CategoryCatalogResultsHeader_defaults,
      render: (props) => <CategoryCatalogResultsHeaderView {...props} />,
    },
    CategoryCatalogResultsState: {
      category: "Categories",
      label: "Category Results State",
      fields: CategoryCatalogResultsState_fields,
      defaultProps: CategoryCatalogResultsState_defaults,
      render: (props) => <CategoryCatalogResultsStateView {...props} />,
    },
    CategoryCatalogStateSection: {
      category: "Categories",
      label: "Category Catalog State Section",
      fields: CategoryCatalogStateSection_fields,
      defaultProps: CategoryCatalogStateSection_defaults,
      render: (props) => <CategoryCatalogStateSectionView {...props} />,
    },
    CategoryGrid: {
      category: "Categories",
      label: "Category Grid",
      fields: CategoryGrid_fields,
      defaultProps: CategoryGrid_defaults,
      render: (props) => <CategoryGridView {...props} />,
    },
    CategoryHero: {
      category: "Categories",
      label: "Category Hero",
      fields: CategoryHero_fields,
      defaultProps: CategoryHero_defaults,
      render: (props) => <CategoryHeroView {...props} />,
    },
    CategoryHighlights: {
      category: "Home",
      label: "Category Highlights",
      fields: CategoryHighlights_fields,
      defaultProps: CategoryHighlights_defaults,
      render: (props) => <CategoryHighlightsView {...props} />,
    },
    CategoryProductFiltersBlock: {
      category: "Categories",
      label: "Category Product Filters",
      fields: CategoryProductFiltersBlock_fields,
      defaultProps: CategoryProductFiltersBlock_defaults,
      render: (props) => <CategoryProductFiltersBlockView {...props} />,
    },
    CategoryProductGridBlock: {
      category: "Categories",
      label: "Category Product Grid",
      fields: CategoryProductGridBlock_fields,
      defaultProps: CategoryProductGridBlock_defaults,
      render: (props) => <CategoryProductGridBlockView {...props} />,
    },
    CategorySubcategoryCondition: {
      category: "Categories",
      label: "Sibling Category Condition",
      fields: CategorySubcategoryCondition_fields,
      defaultProps: CategorySubcategoryCondition_defaults,
      render: (props) => <CategorySubcategoryConditionView {...props} />,
    },
    CheckoutConfirmation: {
      category: "Checkout",
      label: "Checkout Confirmation",
      fields: CheckoutConfirmation_fields,
      defaultProps: CheckoutConfirmation_defaults,
      render: (props) => <CheckoutConfirmationView {...props} />,
    },
    CheckoutDigitalAssetsSection: {
      category: "Checkout",
      label: "Checkout Digital Assets Section",
      fields: CheckoutDigitalAssetsSection_fields,
      defaultProps: CheckoutDigitalAssetsSection_defaults,
      render: (props) => <CheckoutDigitalAssetsSectionView {...props} />,
    },
    CheckoutOrderReview: {
      category: "Checkout",
      label: "Checkout Order Review",
      fields: CheckoutOrderReview_fields,
      defaultProps: CheckoutOrderReview_defaults,
      render: (props) => <CheckoutOrderReviewView {...props} />,
    },
    CheckoutOrderSummary: {
      category: "Checkout",
      label: "Checkout Order Summary",
      fields: CheckoutOrderSummary_fields,
      defaultProps: CheckoutOrderSummary_defaults,
      render: (props) => <CheckoutOrderSummaryView {...props} />,
    },
    CheckoutPaymentMethod: {
      category: "Checkout",
      label: "Checkout Payment Method",
      fields: CheckoutPaymentMethod_fields,
      defaultProps: CheckoutPaymentMethod_defaults,
      render: (props) => <CheckoutPaymentMethodView {...props} />,
    },
    CheckoutPlaceOrderButton: {
      category: "Checkout",
      label: "Place Order Button",
      fields: CheckoutPlaceOrderButton_fields,
      defaultProps: CheckoutPlaceOrderButton_defaults,
      render: (props) => <CheckoutPlaceOrderButtonView {...props} />,
    },
    CheckoutSecureBadges: {
      category: "Checkout",
      label: "Secure Checkout Badges",
      fields: CheckoutSecureBadges_fields,
      defaultProps: CheckoutSecureBadges_defaults,
      render: (props) => <CheckoutSecureBadgesView {...props} />,
    },
    CheckoutShippingForm: {
      category: "Checkout",
      label: "Checkout Shipping Form",
      fields: CheckoutShippingForm_fields,
      defaultProps: CheckoutShippingForm_defaults,
      render: (props) => <CheckoutShippingFormView {...props} />,
    },
    CheckoutShippingMethod: {
      category: "Checkout",
      label: "Checkout Shipping Method",
      fields: CheckoutShippingMethod_fields,
      defaultProps: CheckoutShippingMethod_defaults,
      render: (props) => <CheckoutShippingMethodView {...props} />,
    },
    CheckoutStateSection: {
      category: "Checkout",
      label: "Checkout State Section",
      fields: CheckoutStateSection_fields,
      defaultProps: CheckoutStateSection_defaults,
      render: (props) => <CheckoutStateSectionView {...props} />,
    },
    CheckoutSteps: {
      category: "Checkout",
      label: "Checkout Steps Progress",
      fields: CheckoutSteps_fields,
      defaultProps: CheckoutSteps_defaults,
      render: (props) => <CheckoutStepsView {...props} />,
    },
    CheckoutSubscriptionStateSection: {
      category: "Checkout",
      label: "Checkout Subscription State Section",
      fields: CheckoutSubscriptionStateSection_fields,
      defaultProps: CheckoutSubscriptionStateSection_defaults,
      render: (props) => <CheckoutSubscriptionStateSectionView {...props} />,
    },
    CollectionDetailStateSection: {
      category: "Collections",
      label: "Collection Detail State Section",
      fields: CollectionDetailStateSection_fields,
      defaultProps: CollectionDetailStateSection_defaults,
      render: (props) => <CollectionDetailStateSectionView {...props} />,
    },
    CollectionGrid: {
      category: "Collections",
      label: "Collection Grid",
      fields: CollectionGrid_fields,
      defaultProps: CollectionGrid_defaults,
      render: (props) => <CollectionGridView {...props} />,
    },
    CollectionHero: {
      category: "Collections",
      label: "Collection Hero",
      fields: CollectionHero_fields,
      defaultProps: CollectionHero_defaults,
      render: (props) => <CollectionHeroView {...props} />,
    },
    CollectionStateSection: {
      category: "Collections",
      label: "Collection State Section",
      fields: CollectionStateSection_fields,
      defaultProps: CollectionStateSection_defaults,
      render: (props) => <CollectionStateSectionView {...props} />,
    },
    ConditionalSection: {
      category: "Layout",
      label: "Conditional Section",
      fields: ConditionalSection_fields,
      defaultProps: ConditionalSection_defaults,
      render: (props) => <ConditionalSectionView {...props} />,
    },
    ConfirmationOrderSummary: {
      category: "Checkout",
      label: "Order Summary",
      fields: ConfirmationOrderSummary_fields,
      defaultProps: ConfirmationOrderSummary_defaults,
      render: (props) => <OrderSummaryView {...props} />,
    },
    ContinueShoppingButton: {
      category: "Checkout",
      label: "Continue Shopping Button",
      fields: ContinueShoppingButton_fields,
      defaultProps: ContinueShoppingButton_defaults,
      render: (props) => <ContinueShoppingButtonView {...props} />,
    },
    CuratedCollectionSection: {
      category: "Home",
      label: "Curated Collection Section",
      fields: CuratedCollectionSection_fields,
      defaultProps: CuratedCollectionSection_defaults,
      render: (props) => <CuratedCollectionSectionView {...props} />,
    },
    CuratedProductDisplay: {
      category: "Collections",
      label: "Curated Product Display",
      fields: CuratedProductDisplay_fields,
      defaultProps: CuratedProductDisplay_defaults,
      render: (props) => <CuratedProductDisplayView {...props} />,
    },
    DepartmentCategoriesSection: {
      category: "Categories",
      label: "Browse by Department Section",
      fields: DepartmentCategoriesSection_fields,
      defaultProps: DepartmentCategoriesSection_defaults,
      render: (props) => <DepartmentCategoriesSectionView {...props} />,
    },
    DigitalDownloads: {
      category: "Checkout",
      label: "Digital Downloads",
      fields: DigitalDownloads_fields,
      defaultProps: DigitalDownloads_defaults,
      render: (props) => <DigitalDownloadsView {...props} />,
    },
    DownloadLicenseStateSection: {
      category: "Downloads",
      label: "Download License State Section",
      fields: DownloadLicenseStateSection_fields,
      defaultProps: DownloadLicenseStateSection_defaults,
      render: (props) => <DownloadLicenseStateSectionView {...props} />,
    },
    DownloadsEmpty: {
      category: "Account",
      label: "Downloads Empty State",
      fields: DownloadsEmpty_fields,
      defaultProps: DownloadsEmpty_defaults,
      render: (props) => <DownloadsEmptyView {...props} />,
    },
    EmptyCategory: {
      category: "Categories",
      label: "Empty Category State",
      fields: EmptyCategory_fields,
      defaultProps: EmptyCategory_defaults,
      render: (props) => <EmptyCategoryView {...props} />,
    },
    EmptyCollections: {
      category: "Collections",
      label: "Empty Collections State",
      fields: EmptyCollections_fields,
      defaultProps: EmptyCollections_defaults,
      render: (props) => <EmptyCollectionsView {...props} />,
    },
    EmptyPaymentMethods: {
      category: "Account",
      label: "Empty Payment Methods",
      fields: EmptyPaymentMethods_fields,
      defaultProps: EmptyPaymentMethods_defaults,
      render: (props) => <EmptyPaymentMethodsView {...props} />,
    },
    EmptyState: {
      category: "Products",
      label: "Empty Product State",
      fields: EmptyState_fields,
      defaultProps: EmptyState_defaults,
      render: (props) => <EmptyStateView {...props} />,
    },
    ErrorState: {
      category: "Feedback",
      label: "Error State",
      fields: ErrorState_fields,
      defaultProps: ErrorState_defaults,
      render: (props) => <ErrorStateView {...props} />,
    },
    FeaturedProductsGrid: {
      category: "Home",
      label: "Featured Products Grid",
      fields: FeaturedProductsGrid_fields,
      defaultProps: FeaturedProductsGrid_defaults,
      render: (props) => <FeaturedProductsGridView {...props} />,
    },
    FeatureIconList: {
      category: "Layout",
      label: "Feature Icon List",
      fields: FeatureIconList_fields,
      defaultProps: FeatureIconList_defaults,
      render: (props) => <FeatureIconListView {...props} />,
    },
    FreeShippingProgress: {
      category: "Cart",
      label: "Free Shipping Progress",
      fields: FreeShippingProgress_fields,
      defaultProps: FreeShippingProgress_defaults,
      render: (props) => <FreeShippingProgressView {...props} />,
    },
    HeroSection: {
      category: "Home",
      label: "Hero Section",
      fields: HeroSection_fields,
      defaultProps: HeroSection_defaults,
      render: (props) => <HeroSectionView {...props} />,
    },
    InspirationGallery: {
      category: "Collections",
      label: "Inspiration Gallery",
      fields: InspirationGallery_fields,
      defaultProps: InspirationGallery_defaults,
      render: (props) => <InspirationGalleryView {...props} />,
    },
    InspirationSection: {
      category: "Home",
      label: "Inspiration Section",
      fields: InspirationSection_fields,
      defaultProps: InspirationSection_defaults,
      render: (props) => <InspirationSectionView {...props} />,
    },
    LicenseKeyDisplay: {
      category: "Checkout",
      label: "License Key Display",
      fields: LicenseKeyDisplay_fields,
      defaultProps: LicenseKeyDisplay_defaults,
      render: (props) => <LicenseKeyDisplayView {...props} />,
    },
    MobileFilterDrawerBlock: {
      category: "Products",
      label: "Mobile Filter Drawer",
      fields: MobileFilterDrawerBlock_fields,
      defaultProps: MobileFilterDrawerBlock_defaults,
      render: (props) => <MobileFilterDrawerBlockView {...props} />,
    },
    NewsletterSignup: {
      category: "Home",
      label: "Newsletter Signup",
      fields: NewsletterSignup_fields,
      defaultProps: NewsletterSignup_defaults,
      render: (props) => <NewsletterSignupView {...props} />,
    },
    NextStepsCard: {
      category: "Checkout",
      label: "Next Steps Card",
      fields: NextStepsCard_fields,
      defaultProps: NextStepsCard_defaults,
      render: (props) => <NextStepsCardView {...props} />,
    },
    NoResults: {
      category: "Search",
      label: "No Search Results",
      fields: NoResults_fields,
      defaultProps: NoResults_defaults,
      render: (props) => <NoResultsView {...props} />,
    },
    NotEligibleMessage: {
      category: "Account",
      label: "Not Eligible for Return",
      fields: NotEligibleMessage_fields,
      defaultProps: NotEligibleMessage_defaults,
      render: (props) => <NotEligibleMessageView {...props} />,
    },
    NotFoundState: {
      category: "Feedback",
      label: "Not Found State",
      fields: NotFoundState_fields,
      defaultProps: NotFoundState_defaults,
      render: (props) => <NotFoundStateView {...props} />,
    },
    OrderDetails: {
      category: "Account",
      label: "Order Details (Financial)",
      fields: OrderDetails_fields,
      defaultProps: OrderDetails_defaults,
      render: (props) => <OrderDetailsView {...props} />,
    },
    OrderEmpty: {
      category: "Account",
      label: "Order Empty State",
      fields: OrderEmpty_fields,
      defaultProps: OrderEmpty_defaults,
      render: (props) => <OrderEmptyView {...props} />,
    },
    OrderItemList: {
      category: "Checkout",
      label: "Order Item List",
      fields: OrderItemList_fields,
      defaultProps: OrderItemList_defaults,
      render: (props) => <OrderItemListView {...props} />,
    },
    OrderNumber: {
      category: "Checkout",
      label: "Order Number",
      fields: OrderNumber_fields,
      defaultProps: OrderNumber_defaults,
      render: (props) => <OrderNumberView {...props} />,
    },
    OrderStatusBadge: {
      category: "Account",
      label: "Order Status Badge",
      fields: OrderStatusBadge_fields,
      defaultProps: OrderStatusBadge_defaults,
      render: (props) => <OrderStatusBadgeView {...props} />,
    },
    PageHeader: {
      category: "Layout",
      label: "Page Header",
      fields: PageHeader_fields,
      defaultProps: PageHeader_defaults,
      render: (props) => <PageHeaderView {...props} />,
    },
    PageWrapper: {
      category: "Layout",
      label: "Page Wrapper",
      fields: PageWrapper_fields,
      defaultProps: PageWrapper_defaults,
      render: (props) => <PageWrapperView {...props} />,
    },
    PaymentInfo: {
      category: "Account",
      label: "Payment Info",
      fields: PaymentInfo_fields,
      defaultProps: PaymentInfo_defaults,
      render: (props) => <PaymentInfoView {...props} />,
    },
    PriceDisplay: {
      category: "Products",
      label: "Price Display",
      fields: PriceDisplay_fields,
      defaultProps: PriceDisplay_defaults,
      render: (props) => <PriceDisplayView {...props} />,
    },
    ProductDetailMediaColumn: {
      category: "Products",
      label: "Product Detail Media Column",
      fields: ProductDetailMediaColumn_fields,
      defaultProps: ProductDetailMediaColumn_defaults,
      render: (props) => <ProductDetailMediaColumnView {...props} />,
    },
    ProductDetailMobileTabs: {
      category: "Products",
      label: "Product Detail Mobile Tabs",
      fields: ProductDetailMobileTabs_fields,
      defaultProps: ProductDetailMobileTabs_defaults,
      render: (props) => <ProductDetailMobileTabsView {...props} />,
    },
    ProductDetailPageLayout: {
      category: "Products",
      label: "Product Detail Page Layout",
      fields: ProductDetailPageLayout_fields,
      defaultProps: ProductDetailPageLayout_defaults,
      render: (props) => <ProductDetailPageLayoutView {...props} />,
    },
    ProductDetailPurchaseColumn: {
      category: "Products",
      label: "Product Detail Purchase Column",
      fields: ProductDetailPurchaseColumn_fields,
      defaultProps: ProductDetailPurchaseColumn_defaults,
      render: (props) => <ProductDetailPurchaseColumnView {...props} />,
    },
    ProductDetailPurchaseSection: {
      category: "Products",
      label: "Product Detail Purchase Section",
      fields: ProductDetailPurchaseSection_fields,
      defaultProps: ProductDetailPurchaseSection_defaults,
      render: (props) => <ProductDetailPurchaseSectionView {...props} />,
    },
    ProductDetailRelatedProductsSection: {
      category: "Products",
      label: "Product Detail Related Products Condition",
      fields: ProductDetailRelatedProductsSection_fields,
      defaultProps: ProductDetailRelatedProductsSection_defaults,
      render: (props) => <ProductDetailRelatedProductsSectionView {...props} />,
    },
    ProductDetailsClient: {
      category: "Products",
      label: "Product Details (Add to Cart)",
      fields: ProductDetailsClient_fields,
      defaultProps: ProductDetailsClient_defaults,
      render: (props) => <ProductDetailsClientView {...props} />,
    },
    ProductDetailSection: {
      category: "Products",
      label: "Product Detail Content Section",
      fields: ProductDetailSection_fields,
      defaultProps: ProductDetailSection_defaults,
      render: (props) => <ProductDetailSectionView {...props} />,
    },
    ProductDetailTrustBadges: {
      category: "Products",
      label: "Product Detail Shipping and Returns",
      fields: ProductDetailTrustBadges_fields,
      defaultProps: ProductDetailTrustBadges_defaults,
      render: (props) => <ProductDetailTrustBadgesView {...props} />,
    },
    ProductFiltersBlock: {
      category: "Products",
      label: "Product Filter Sidebar",
      fields: ProductFiltersBlock_fields,
      defaultProps: ProductFiltersBlock_defaults,
      render: (props) => <ProductFiltersBlockView {...props} />,
    },
    ProductGallery: {
      category: "Products",
      label: "Product Gallery",
      fields: ProductGallery_fields,
      defaultProps: ProductGallery_defaults,
      render: (props) => <ProductGalleryView {...props} />,
    },
    ProductGrid: {
      category: "Products",
      label: "Product Grid",
      fields: ProductGrid_fields,
      defaultProps: ProductGrid_defaults,
      render: (props) => <ProductGridView {...props} />,
    },
    ProductRatingSummary: {
      category: "Products",
      label: "Product Rating Summary",
      fields: ProductRatingSummary_fields,
      defaultProps: ProductRatingSummary_defaults,
      render: (props) => <ProductRatingSummaryView {...props} />,
    },
    ProductRelatedProductsSection: {
      category: "Products",
      label: "Product Related Products Section",
      fields: ProductRelatedProductsSection_fields,
      defaultProps: ProductRelatedProductsSection_defaults,
      render: (props) => <ProductRelatedProductsSectionView {...props} />,
    },
    ProductsCatalogLayout: {
      category: "Products",
      label: "Products Catalog Layout",
      fields: ProductsCatalogLayout_fields,
      defaultProps: ProductsCatalogLayout_defaults,
      render: (props) => <ProductsCatalogLayoutView {...props} />,
    },
    ProductsCatalogStateSection: {
      category: "Products",
      label: "Products Catalog State Section",
      fields: ProductsCatalogStateSection_fields,
      defaultProps: ProductsCatalogStateSection_defaults,
      render: (props) => <ProductsCatalogStateSectionView {...props} />,
    },
    ProductTabs: {
      category: "Products",
      label: "Product Tabs",
      fields: ProductTabs_fields,
      defaultProps: ProductTabs_defaults,
      render: (props) => <ProductTabsView {...props} />,
    },
    PromotionBanner: {
      category: "Marketing",
      label: "Promotion Banner",
      fields: PromotionBanner_fields,
      defaultProps: PromotionBanner_defaults,
      render: (props) => <PromotionBannerView {...props} />,
    },
    PurchaseTracker: {
      category: "Checkout",
      label: "Purchase Tracker",
      fields: PurchaseTracker_fields,
      defaultProps: PurchaseTracker_defaults,
      render: (props) => <PurchaseTrackerView {...props} />,
    },
    RefundSummary: {
      category: "Account",
      label: "Refund Summary",
      fields: RefundSummary_fields,
      defaultProps: RefundSummary_defaults,
      render: (props) => <RefundSummaryView {...props} />,
    },
    RelatedProducts: {
      category: "Products",
      label: "Related Products",
      fields: RelatedProducts_fields,
      defaultProps: RelatedProducts_defaults,
      render: (props) => <RelatedProductsView {...props} />,
    },
    ReturnPolicyReminder: {
      category: "Account",
      label: "Return Policy Reminder",
      fields: ReturnPolicyReminder_fields,
      defaultProps: ReturnPolicyReminder_defaults,
      render: (props) => <ReturnPolicyReminderView {...props} />,
    },
    ReturnReason: {
      category: "Account",
      label: "Return Reason",
      fields: ReturnReason_fields,
      defaultProps: ReturnReason_defaults,
      render: (props) => <ReturnReasonView {...props} />,
    },
    ReturnsEmpty: {
      category: "Account",
      label: "Returns Empty State",
      fields: ReturnsEmpty_fields,
      defaultProps: ReturnsEmpty_defaults,
      render: (props) => <ReturnsEmptyView {...props} />,
    },
    ReturnStatusBadge: {
      category: "Account",
      label: "Return Status Badge",
      fields: ReturnStatusBadge_fields,
      defaultProps: ReturnStatusBadge_defaults,
      render: (props) => <ReturnStatusBadgeView {...props} />,
    },
    ReturnWindowExpired: {
      category: "Account",
      label: "Return Window Expired",
      fields: ReturnWindowExpired_fields,
      defaultProps: ReturnWindowExpired_defaults,
      render: (props) => <ReturnWindowExpiredView {...props} />,
    },
    ReviewsSection: {
      category: "Products",
      label: "Reviews Section",
      fields: ReviewsSection_fields,
      defaultProps: ReviewsSection_defaults,
      render: (props) => <ReviewsSectionView {...props} />,
    },
    SearchHeader: {
      category: "Search",
      label: "Search Header",
      fields: SearchHeader_fields,
      defaultProps: SearchHeader_defaults,
      render: (props) => <SearchHeaderView {...props} />,
    },
    SearchStateSection: {
      category: "Search",
      label: "Search State Section",
      fields: SearchStateSection_fields,
      defaultProps: SearchStateSection_defaults,
      render: (props) => <SearchStateSectionView {...props} />,
    },
    SectionHeaderWithDivider: {
      category: "Layout",
      label: "Section Header With Divider",
      fields: SectionHeaderWithDivider_fields,
      defaultProps: SectionHeaderWithDivider_defaults,
      render: (props) => <SectionHeaderWithDividerView {...props} />,
    },
    SectionHeading: {
      category: "Layout",
      label: "Section Heading",
      fields: SectionHeading_fields,
      defaultProps: SectionHeading_defaults,
      render: (props) => <SectionHeadingView {...props} />,
    },
    SharedWishlist: {
      category: "Account",
      label: "Shared Wishlist",
      fields: SharedWishlist_fields,
      defaultProps: SharedWishlist_defaults,
      render: (props) => <SharedWishlistView {...props} />,
    },
    SharedWishlistStateSection: {
      category: "Wishlist",
      label: "Shared Wishlist State Section",
      fields: SharedWishlistStateSection_fields,
      defaultProps: SharedWishlistStateSection_defaults,
      render: (props) => <SharedWishlistStateSectionView {...props} />,
    },
    ShippingAddress: {
      category: "Account",
      label: "Shipping Address",
      fields: ShippingAddress_fields,
      defaultProps: ShippingAddress_defaults,
      render: (props) => <ShippingAddressView {...props} />,
    },
    ShippingInfo: {
      category: "Checkout",
      label: "Shipping Info",
      fields: ShippingInfo_fields,
      defaultProps: ShippingInfo_defaults,
      render: (props) => <ShippingInfoView {...props} />,
    },
    SortDropdownBlock: {
      category: "Products",
      label: "Catalog Sort Dropdown",
      fields: SortDropdownBlock_fields,
      defaultProps: SortDropdownBlock_defaults,
      render: (props) => <SortDropdownBlockView {...props} />,
    },
    StockIndicator: {
      category: "Products",
      label: "Stock Indicator",
      fields: StockIndicator_fields,
      defaultProps: StockIndicator_defaults,
      render: (props) => <StockIndicatorView {...props} />,
    },
    SubcategoryNav: {
      category: "Categories",
      label: "Subcategory Navigation",
      fields: SubcategoryNav_fields,
      defaultProps: SubcategoryNav_defaults,
      render: (props) => <SubcategoryNavView {...props} />,
    },
    SubscriptionDetailsHeader: {
      category: "Account",
      label: "Subscription Details Header",
      fields: SubscriptionDetailsHeader_fields,
      defaultProps: SubscriptionDetailsHeader_defaults,
      render: (props) => <SubscriptionDetailsHeaderView {...props} />,
    },
    SubscriptionDetailStateSection: {
      category: "Account",
      label: "Subscription Detail State Section",
      fields: SubscriptionDetailStateSection_fields,
      defaultProps: SubscriptionDetailStateSection_defaults,
      render: (props) => <SubscriptionDetailStateSectionView {...props} />,
    },
    SubscriptionsEmpty: {
      category: "Account",
      label: "Subscriptions Empty State",
      fields: SubscriptionsEmpty_fields,
      defaultProps: SubscriptionsEmpty_defaults,
      render: (props) => <SubscriptionsEmptyView {...props} />,
    },
    SubscriptionStatusBadge: {
      category: "Account",
      label: "Subscription Status Badge",
      fields: SubscriptionStatusBadge_fields,
      defaultProps: SubscriptionStatusBadge_defaults,
      render: (props) => <SubscriptionStatusBadgeView {...props} />,
    },
    SuccessHeader: {
      category: "Checkout",
      label: "Success Header",
      fields: SuccessHeader_fields,
      defaultProps: SuccessHeader_defaults,
      render: (props) => <SuccessHeaderView {...props} />,
    },
    TestimonialsSection: {
      category: "Social Proof",
      label: "Testimonials Section",
      fields: TestimonialsSection_fields,
      defaultProps: TestimonialsSection_defaults,
      render: (props) => <TestimonialsSectionView {...props} />,
    },
    TrendingCategoriesSection: {
      category: "Categories",
      label: "Trending Categories Section",
      fields: TrendingCategoriesSection_fields,
      defaultProps: TrendingCategoriesSection_defaults,
      render: (props) => <TrendingCategoriesSectionView {...props} />,
    },
    TrendingCategoryCard: {
      category: "Categories",
      label: "Trending Category Card",
      fields: TrendingCategoryCard_fields,
      defaultProps: TrendingCategoryCard_defaults,
      render: (props) => <TrendingCategoryCardView {...props} />,
    },
    TrustBadges: {
      category: "Home",
      label: "Trust Badges",
      fields: TrustBadges_fields,
      defaultProps: TrustBadges_defaults,
      render: (props) => <TrustBadges {...props} />,
    },
    TwoColumnDetail: {
      category: "Layout",
      label: "Two Column Detail",
      fields: TwoColumnDetail_fields,
      defaultProps: TwoColumnDetail_defaults,
      render: (props) => <TwoColumnDetailView {...props} />,
    },
    ViewOrderButton: {
      category: "Checkout",
      label: "View Order Button",
      fields: ViewOrderButton_fields,
      defaultProps: ViewOrderButton_defaults,
      render: (props) => <ViewOrderButtonView {...props} />,
    },
    ViewToggleBlock: {
      category: "Products",
      label: "Catalog View Toggle",
      fields: ViewToggleBlock_fields,
      defaultProps: ViewToggleBlock_defaults,
      render: (props) => <ViewToggleBlockView {...props} />,
    },
    WishlistEmpty: {
      category: "Account",
      label: "Wishlist Empty State",
      fields: WishlistEmpty_fields,
      defaultProps: WishlistEmpty_defaults,
      render: (props) => <WishlistEmptyView {...props} />,
    },
    WishlistSavingsCard: {
      category: "Account",
      label: "Wishlist Savings Card",
      fields: WishlistSavingsCard_fields,
      defaultProps: WishlistSavingsCard_defaults,
      render: (props) => <WishlistSavingsCardView {...props} />,
    },
  },
};

export default config;
