'use client';

import { cn } from '@/lib/utils/cn';
import { CHECKOUT_STEPS } from '@/lib/utils/constants';
import type { Cart } from '@/lib/api/types/cart';
import type { ProductSellingPlansResponse, SubscriptionPreview } from '@/lib/api/types/selling-plans';
import CheckoutSteps, { type SubscriptionCheckoutStep } from './CheckoutSteps';
import CustomerInfoForm from './CustomerInfoForm'; import ShippingAddressForm from './ShippingAddressForm'; import BillingTerms from './BillingTerms';
import CheckoutButton from './CheckoutButton'; import StripeRedirectMessage from './StripeRedirectMessage';
import SubscriptionCartSummary, { type SubscriptionCartSummaryItem } from './SubscriptionCartSummary';
import PricingPreviewCard from './PricingPreviewCard'; import FirstBillingPrice from './FirstBillingPrice'; import RecurringPriceDisplay from './RecurringPriceDisplay'; import NextBillingDate from './NextBillingDate'; import SavingsBreakdown from './SavingsBreakdown';
import SubscriptionSummary from './SubscriptionSummary'; import BillingFrequency from './BillingFrequency'; import FirstChargeNotice from './FirstChargeNotice'; import RenewalNotice from './RenewalNotice'; import CancellationPolicy from './CancellationPolicy';

export function SubscriptionCheckoutHeader() { return <div className="space-y-2"><h1 className="text-2xl font-bold tracking-tight @md:text-3xl">Subscription Checkout</h1><p className="text-sm text-text-muted @md:text-base">Complete your subscription checkout.</p></div>; }
export function SubscriptionCheckoutSteps() { const steps: SubscriptionCheckoutStep[] = [{ id: CHECKOUT_STEPS.CART, name: 'Information', completed: false, current: true }, { id: CHECKOUT_STEPS.SHIPPING, name: 'Shipping', completed: false, current: false }, { id: CHECKOUT_STEPS.PAYMENT, name: 'Payment', completed: false, current: false }]; return <CheckoutSteps steps={steps} currentStepId={steps[0].id} />; }
export function SubscriptionCustomerInfoSection({ onChange }: { onChange: (value: { email: string; firstName: string; lastName: string }) => void }) { return <section className="space-y-4"><h2 className="text-xl font-semibold text-text-base">Customer information</h2><CustomerInfoForm onChange={onChange} /></section>; }
export function SubscriptionShippingAddressSection({ onChange }: { onChange: (value: { addressLine1: string; addressLine2: string; city: string; state: string; postalCode: string; country: string }) => void }) { return <section className="space-y-4"><h2 className="text-xl font-semibold text-text-base">Shipping address</h2><ShippingAddressForm onChange={onChange} /></section>; }
export function SubscriptionBillingTermsSection({ checked, termsText, policyText, onChange }: { checked: boolean; termsText: string; policyText: string; onChange: (checked: boolean) => void }) { return <section className="space-y-4 border-t border-border pt-6"><h2 className="text-xl font-semibold text-text-base">Billing terms</h2><BillingTerms checked={checked} termsText={termsText} policyText={policyText} onChange={onChange} /></section>; }
export function SubscriptionCheckoutError({ message }: { message?: string | null }) { return message ? <div className={cn('@container w-full rounded-card border border-danger bg-danger-subtle px-4 py-3 text-sm text-danger')}>{message}</div> : null; }
export function SubscriptionCartSummaryPanel({ cart, sellingPlans, pricingPreview }: { cart: Cart; sellingPlans: ProductSellingPlansResponse | null; pricingPreview: SubscriptionPreview | null }) { const items: SubscriptionCartSummaryItem[] = cart.items.map((item) => { const planId = (item as { sellingPlanId?: string }).sellingPlanId; const plan = planId ? sellingPlans?.sellingPlans.find((candidate) => candidate.id === planId) : sellingPlans?.sellingPlans[0]; const preview = pricingPreview?.product.id === item.productId ? pricingPreview : null; return { id: item.productId, name: item.product.name, imageUrl: item.product.imageUrl || item.product.images?.[0], imageAlt: item.product.name, quantity: item.quantity, sellingPlanLabel: plan?.name || preview?.sellingPlan.name, intervalLabel: preview?.sellingPlan.intervalLabel || plan?.intervalLabel, recurringPrice: preview?.pricing.recurringPrice || plan?.discountedPrice, originalPrice: plan?.originalPrice || item.product.originalPrice || item.product.price, savingsAmount: preview?.pricing.savings.total, savingsPercent: preview?.pricing.savings.percent || plan?.savingsPercent }; }); return <SubscriptionCartSummary items={items} />; }
export function SubscriptionPricingPreviewPanel({ pricingPreview }: { pricingPreview: SubscriptionPreview | null }) { return <PricingPreviewCard>{pricingPreview ? <><FirstBillingPrice amount={pricingPreview.pricing.firstBillingPrice} /><RecurringPriceDisplay amount={pricingPreview.pricing.recurringPrice} intervalLabel={pricingPreview.sellingPlan.intervalLabel} /><NextBillingDate date={pricingPreview.nextBillingDate} /><SavingsBreakdown perUnit={pricingPreview.pricing.savings.perUnit} total={pricingPreview.pricing.savings.total} percent={pricingPreview.pricing.savings.percent} /></> : <p className="text-sm text-text-muted">Pricing preview unavailable.</p>}</PricingPreviewCard>; }
export function SubscriptionTermsSummaryPanel({ cart, sellingPlans, pricingPreview }: { cart: Cart; sellingPlans: ProductSellingPlansResponse | null; pricingPreview: SubscriptionPreview | null }) { const planId = (cart.items[0] as { sellingPlanId?: string } | undefined)?.sellingPlanId; const intervalLabel = pricingPreview?.sellingPlan.intervalLabel || (planId ? sellingPlans?.sellingPlans.find((plan) => plan.id === planId)?.intervalLabel : sellingPlans?.sellingPlans[0]?.intervalLabel); return <SubscriptionSummary>{intervalLabel ? <BillingFrequency intervalLabel={intervalLabel} /> : null}<FirstChargeNotice amount={pricingPreview?.pricing.firstBillingPrice} />{intervalLabel ? <RenewalNotice intervalLabel={intervalLabel.toLowerCase()} /> : null}<CancellationPolicy policyText="You can cancel anytime from your account dashboard." /></SubscriptionSummary>; }
export function SubscriptionCheckoutActions({ onCheckout, isProcessing, disabled }: { onCheckout: () => void; isProcessing: boolean; disabled: boolean }) { return <div className="space-y-3"><CheckoutButton onClick={onCheckout} isLoading={isProcessing} disabled={disabled} /><StripeRedirectMessage /></div>; }
