import { CheckoutSuccessDigitalAssetsCondition } from './CheckoutSuccessDigitalAssetsCondition';
import { loadCheckoutSuccessRuntime } from './checkoutSuccessRuntime';
import { puckTransparentSlotProps, type CheckoutSuccessSlot } from './types';

interface Props { available?: boolean; previewMode?: 'visible' | 'hidden'; content?: CheckoutSuccessSlot; puck?: { isEditing?: boolean }; }
export const puckComponentName = 'CheckoutSuccessDigitalAssetsCondition'; export const puckLabel = 'Checkout Success Digital Assets Condition'; export const puckCategory = 'Checkout';
export const puckFields = { previewMode: { type: 'select' as const, options: [{ label: 'Visible', value: 'visible' }, { label: 'Hidden', value: 'hidden' }] }, content: { type: 'slot' as const, allow: ['CheckoutSuccessDigitalDownloads', 'CheckoutSuccessLicenseKeys'] } }; export const puckDefaults = { previewMode: 'visible', content: [] };
export const puckAst = { kind: 'runtime', slots: ['content'], sourceJsxNames: ['CheckoutSuccessDigitalAssetsCondition'], sourceImportPaths: ['@/components/checkout/success/canonical/CheckoutSuccessDigitalAssetsCondition'], role: 'checkout-success-digital-assets-condition', conditional: 'digitalAssets && digitalAssets.hasDigitalItems && digitalAssets.assets && digitalAssets.assets.length > 0', runtimeSignals: ['order', 'digitalAssets'] };
export async function puckDataFetcher(_props: Props, context?: Parameters<typeof loadCheckoutSuccessRuntime>[0]) { const runtime = await loadCheckoutSuccessRuntime(context); return { available: Boolean(runtime.digitalAssets && runtime.digitalAssets.hasDigitalItems && runtime.digitalAssets.assets && runtime.digitalAssets.assets.length > 0) }; }
export function CheckoutSuccessDigitalAssetsConditionView({ available, previewMode = 'visible', content, puck }: Props) { const resolved = puck?.isEditing ? previewMode === 'visible' : available ?? false; return <CheckoutSuccessDigitalAssetsCondition available={resolved} content={content?.(puckTransparentSlotProps)} />; }
